import * as secrets from "secrets.js-grempe";

export interface Shard {
  id: number;
  data: string; // The hex string containing shard info generated by secrets.js
}

/**
 * Splits a hex key into multiple shards using Shamir's Secret Sharing.
 * @param hexKey The raw secret (e.g. exported AES key in hex)
 * @param totalShards Number of total pieces 
 * @param threshold Minimum pieces to recover 
 */
export function splitKey(hexKey: string, totalShards: number, threshold: number): Shard[] {
  // Validate inputs
  if (threshold > totalShards) {
    throw new Error("Threshold cannot be greater than total shards.");
  }
  
  // Generate the shares
  const shares = secrets.share(hexKey, totalShards, threshold);
  
  // Format them with extracted IDs for easier management
  return shares.map((shareStr) => {
    const extracted = secrets.extractShareComponents(shareStr);
    return {
      id: extracted ? extracted.id : 0,
      data: shareStr
    };
  });
}

/**
 * Reconstructs the hex key from a sufficient number of shards.
 * @param shards Array of shards (at least `threshold` amount)
 */
export function reconstructKey(shards: Shard[]): string {
  if (shards.length === 0) {
    throw new Error("Cannot reconstruct key with 0 shards.");
  }
  const shareStrings = shards.map(s => s.data);
  return secrets.combine(shareStrings);
}
